### ISSUE TITLE
Seeing ierrors in Stats When Running in STL Mode

### ISSUE THREAD

**Issue by jeremy020** [pensando/trex-core#3]
#### Description
While using trex with STL mode, I noticed that they are a lot of `ierrors` in the stats outputted by trex, and this has an impact on the over all performance of trex application in STL mode. 
#### TRex configuration 
```
interfaces: ['0000:14:00.0', '0000:15:00.0']
  rx_desc: 4096
  port_info:
      - ip: 1.1.1.1
        default_gw: 2.2.2.2
      - ip: 2.2.2.2
        default_gw: 1.1.1.1
  platform:
      master_thread_id: 0
      latency_thread_id: 10
      dual_if:
        - socket: 0
          threads: [1,2,3,4,5,6,7,8,9,20,21,22,23,24,25,26,27,28,29]
```
#### Screenshots
![Screen Shot 2022-07-19 at 3 27 45 PM](https://user-images.githubusercontent.com/106121749/179858990-074da591-9eac-48cf-8b4c-649d26ce4a1d.png)

#### To Reproduce
1. Start trex on one terminal by using `./t-rex-64 -c 10 -i`
2. Start `trex-console` on another terminal using `./trex-console`
3. Then using this command `start -f stl/udp_1pkt_simple.py -m 10000000 -d 100 -p 0` in `trex-console`
