### ISSUE TITLE
Seeing Keepalive Drop Packets when Running in ASTF Mode with UDP Protocol 

### ISSUE THREAD

**Issue by jeremy020** [pensando/trex-core#4]
#### Description

- With multi core: I'm seeing some packet drops when running trex in ASTF mode with UDP protocol. I tried with 1M CPS which gave me around 1600 keepalive packet drops. I'm also seeing this when running at a higher CPS. 
- With single core: I'm seeing half of the transmitted packets are getting dropped due to the keepalive issue. Upon investigation, realized that half of the packets are going into queue 1 and the other half are going into queue 0; however, they should all go to queue 0. 

#### TRex Configuration 
```  
  interfaces: ['0000:14:00.0', '0000:15:00.0']
  rx_desc: 4096
  port_info:
      - ip: 1.1.1.1
        default_gw: 2.2.2.2
      - ip: 2.2.2.2
        default_gw: 1.1.1.1
  platform:
      master_thread_id: 0
      latency_thread_id: 10
      dual_if:
        - socket: 0
          threads: [1,2,3,4,5,6,7,8,9,20,21,22,23,24,25,26,27,28,29]
```
#### Screenshots
![Screen Shot 2022-07-19 at 3 47 17 PM](https://user-images.githubusercontent.com/106121749/179861037-27c9777d-e3c3-4b2c-a3e1-b1af9da0a9a2.png)
#### To Reproduce
1. Start trex on one terminal by using `./t-rex-64 -c 8 -i --astf`
2. Start trex-console on another terminal using `./trex-console`
3. Then using this command `start -f astf/udp1.py -m 10000000 -d 100`  in trex-console
